### ISSUE TITLE
Cant choose Channel using number

### ISSUE THREAD

**Issue by nicbruzzese** [stari4ek/tvirl#17]
Am able to browse and choose channel through epg but cannot key in a channel number and it change to the channel

**Comment by stari4ek** [comment]
Which device are you using?

All EPG/Channels navigation is done by TV App itself. _Live Channels_ on shield/mibox or it's analogue on TVs (Sony/Philips).
TVirl provides information about channels numbers to system TV App.

You can read about TVirl's integration in [the FAQ](https://tvirl.app/faq)
Please provide video of the issue - I will raise an issue on google's tracker (https://issuetracker.google.com/issues/)

**Comment by stari4ek** [comment]
Closing due the lack of info

**Comment by antonioli86** [comment]
I would like to reopen this.
My device - TV - is TCL. In Playllst/EPG I have set the channel number, in the list of channel in the TV app I can see the number but cannot switch channel just using number from remote control - nothing happens.

**Comment by stari4ek** [comment]
I am afraid this issue is on TCL's **System TV App** side.
TVirl does not handle any user interactions (via remote or any other input). It's handled by **system TV App**.
When TV App processes user input (like channel +/-, numbers input for channel number) it sends special command to TVirl like "switch to channel with id: 1432556".

You can verify that it works well on TVirl side - you can install Google's _Live Channels_ and check how it works in it.

**Comment by antonioli86** [comment]
True - in Live Channels works fine.

**Comment by stari4ek** [comment]
I am afraid nothing I can do on TVirl side.
It looks like it's not implemented in TCL's TV App
