### ISSUE TITLE
php/js redirect link doesn't work in 0.4.5.0(1964)

### ISSUE THREAD

**Issue by VirgilClyne** [stari4ek/tvirl#25]
Many Chinese m3u8 link are dynamic address, so i need to use php/js script to generate/composite complete m3u8 link ,example:
[http://teslagram.com/now_proxy.php?channel=1](http://teslagram.com/now_proxy.php?channel=1) 
[http://teslagram.com/now_proxy.php?channel=2](http://teslagram.com/now_proxy.php?channel=2) 

In 0.4.5.0(1964), php/js redirect link in m3u8 file , doesn't work anymore

And I really need "#EXTVLCOPT:http-referrer=" function, glad to see it in the future version

**Comment by stari4ek** [comment]
TVirl uses ExoPlayer as playback backend. Which requires to know stream format when player is preparing - before playback and any network calls.
Cause of it - TVirl tries to identify stream format by stream url. So to identify it as HLS you have next options:

- use .m3u8 in the end of an url path (http://teslagram.com/now_proxy.m3u8?channel=1) - prefferable
- use .m3u8 somewhere in the url (http://teslagram.com/now_proxy.m3u8.php?channel=1)
- redirect to url which matches any of previous rules (this one will be slower, since it prepares with http pregressive stream type and when redirect happens - will re-init with new one

**Comment by stari4ek** [comment]
As a workaround for referrer - try to move headers you need to url itself (after `|`)
You can check playlist which uses it here: https://www.matthuisman.nz/2019/01/live-au-iptv-channels-on-android.html

**Comment by VirgilClyne** [comment]
Thank you for your reply, and php/js redirect link work retruns to normal without ".m3u8" in 0.4.5.0(1988)

And I also use "{url}?type=.m3u8" in the url
example: http://teslagram.com/now_proxy.php?channel=1&type=.m3u8

**Comment by stari4ek** [comment]
yeah. m3u8 in GET query should also work
