### ISSUE TITLE
No EPG import

### ISSUE THREAD

**Issue by Heimatkanal** [stari4ek/tvirl#32]
Hello,
Can someone tell me what am I doing wrong? TVirl does not import EPG. Logo: yes but no EPG.

My m3u:
#EXTM3U
#EXTINF:-1 tvg-id="htv1.hr" tvg-name="HTV1" tvg-logo="https://cdn-0.tvprofil.com/cdn/400x200/4/img/kanali-logo/htv1-logo.png",HTV1
http://url/1:0:1F:3E9:17:20BF:EEEE0000:0:0:0:

EPG Import:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tv source-data-url="http://api.tvprofil.net/" source-info-name="TvProfil API v1.7 - XMLTV" source-info-url="https://tvprofil.com">
<channel id="htv1.hr">
<display-name>HTV1</display-name>
<url>http://www.hrt.hr</url>
<icon src="https://cdn-0.tvprofil.com/cdn/400x200/4/img/kanali-logo/htv1-logo.png" />
</channel>`

Thank you!

**Comment by stari4ek** [comment]
Did you specify EPG resource during playlist installation?
Since your playlist does not specify it (using `tvg-url`) you have to specify it manually via UI **during playlist installation**.
Be sure that you **complete** installation with EPG specified. You can not add EPG after installation.

Please send error report from TVirl's menu after installing playlist if it does not help.

**Comment by stari4ek** [comment]
Closing since no info provided
