### ISSUE TITLE
TCL: Cant choose channel using number

### ISSUE THREAD

**Issue by antonioli86** [stari4ek/tvirl#35]
Same as https://github.com/stari4ek/tvirl/issues/17 (closed).
My device - TV - is TCL. In Playllst/EPG I have set the channel number, in the list of channel in the TV app I can see the number but cannot switch channel just using number from remote control - nothing happens.

**Comment by antonioli86** [comment]
Change channel in TV - from tuner - works - but in TVirl not. Video here: 
https://streamable.com/9euz92

I believe is quite clear the behavior in the video.

**Comment by stari4ek** [comment]
@antonioli86, thank you for the video.
But the problem is still the same (#17).

TVirl does not handle input from remote at all. It's implemented by system TV App.
This kind of interactions between system/TV App and "TV input App" (=TVirl) are designed by Google in the way that TVirl does not have access to remote input.

System TV App should send special command to TVirl like "tune to channel with id 145667" after entering channel's number.

BTW, from this video it looks like your TV streaming uses totally different App since it has different interface (comparing list of channels presented for TVirl and for cable/satellite)

**Comment by stari4ek** [comment]
@antonioli86, please send error report from TVirl menu after attempt to switch channel using it's number in system TV App. and another one after switching using Live Channels.

I will double check it

**Comment by antonioli86** [comment]
Reported.
ref: hxKqUAK91EJCX0kgEQCo - using it's number in system TV App
ref: YPA5yLpqZrohZYRHJJ6t - after switching using Live Channels.

**Comment by antonioli86** [comment]
@stari4ek Had you chance to check the logs? :)

**Comment by stari4ek** [comment]
Checked the logs you sent.
As expected no key events bypassed from TV App/system (and this is expected behavior as it's designed by Google (https://source.android.com/devices/tv?hl=en#permissions):
> Only **signatureOrSystem** TV Inputs and TV App have full access to the TV Provider database and are able to receive KeyEvents.

The only communication from TV App/System TVirl gets is via `TvInputService.Session.onTune` which is called **after** TV App processes user's input (from remote using CH+ or CH-, or entering channel number or voice command)
