### ISSUE TITLE
m3u4u: 429 too many requests

### ISSUE THREAD

**Issue by antonioli86** [stari4ek/tvirl#36]
Cannot download playlist from m3u4u - error 429 too many requests.
Using browser can download. Please fix.

**Comment by antonioli86** [comment]
Issue persists.

**Comment by stari4ek** [comment]
Please send error report from TVirl main menu after getting this issue.

**Comment by antonioli86** [comment]
Just reported: 
ref: euKOJxntnQ6BwdjSB9bM

I contacted m3u4u and is not issue from their side since I can download the playlist using other clients.

**Comment by stari4ek** [comment]
According to an investigation, _m3u4u_ blocks GET request if it comes after previous one in 1 minute time frame.
At this moment TVirl forces to ignore local cache and performs clean request for the playlist every time.
So, during playlist configuration it might hit this limitation, since it performs GET twice:
1. fetches playlist to build overview and present playlist/EPG configuration screen
2. fetches playlist during playlist installation

Workarounds:
1. Use "update current playlist" instead of going through full 2-step setup process all the time
2. Wait 1-3 minutes on the playlist configuration screen before playlist installation
3. Do not perform update/install too often

**Comment by antonioli86** [comment]
I need to install the playlist to fix parameters. Please provide instructions - or fix tvirl.15.01.2021, 09:59, "Michael Sotnikov" <notifications@github.com>:
According to an investigation, m3u4u blocks GET request if it comes after previous one in 1 minute time frame.
At this moment TVirl forces to ignore local cache and performs clean request for the playlist every time.
So, during playlist configuration it might hit this limitation, since it performs GET twice:

fetches playlist to build overview and present playlist/EPG configuration screen
fetches playlist during playlist installation

Workarounds:

Use "update current playlist" instead of going through full 2-step setup process all the time
Wait 1-3 minutes on the playlist configuration screen before playlist installation
Do not perform update/install too often

**Comment by stari4ek** [comment]
_m3u4u_ does not provide or honor standard http caching mechanism. So, technically it forces the client to send http GET each time, but it blocks one if it comes in 1 minute time frame.

As a workaround for this crappy policy starting from 0.5.3.0 TVirl will force locally cached response for playlists for 1 minute.
